### PR TITLE
Bypass Trusted Types policy requirement

### LINKED ISSUE #99: Trusted Type API error for pages that rely on a private policy
### Expected behavior

The solution in #71 (to get the default styles of a tag from an iframe) should consistently work..

### Actual behavior (stack traces, console logs etc)

```
This document requires 'TrustedHTML' assignment.
(anonymous) @ VM77:951
VM77:951 Uncaught TypeError: Failed to execute 'write' on 'Document': This document requires 'TrustedHTML' assignment.
    at <anonymous>:951:44
```

(Looping in @joswhite - the [StackOverflow solution](https://stackoverflow.com/a/72204199) needs patching)

Some websites (like the iframe for the invasive Chrome browser callout Google shows to Edge users) propogate a private, non-default Trusted Types API policy. Any attempts to write HTML strings to the DOM need to be wrapped by that policy.

This line throws an error in that case:

https://github.com/1904labs/dom-to-image-more/blob/08a5329b05d861c82ff6468385141cae2dea8f09/src/dom-to-image-more.js#L1001

I didn't think people would be propagating a Trusted Types policy in a private variable.. this means https://github.com/1904labs/dom-to-image-more/issues/90#issuecomment-1358703735 is a false expectation.

We can work around this by something like this:

```js
            const charset = document.createElement('meta');
            charset.setAttribute('charset', document.characterSet || 'UTF-8');
            sandbox.contentDocument.head.appendChild(charset);
            sandbox.contentDocument.title = 'sandbox';
```

(The <title> tag is required in all valid HTML documents so lets add that too...)

### Library version

From [v2.10.1](https://github.com/1904labs/dom-to-image-more/releases/tag/v2.10.1) to [v2.13.1](https://github.com/1904labs/dom-to-image-more/releases/tag/v2.13.1).

### Browsers

- [x] Chrome 49+  
- [x] Firefox 45+

### PR DESCRIPTION
**Pull request by zm-cttae**
Closes #99.

### CODE REVIEW

**Review by IDisposable — APPROVED** [review]
:shipit:

**Comment by joswhite** [comment]
There may be a regression in the new code here. The iframe no longer has `<!DOCTYPE html>`, which means it may render in [Quirks mode](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode). We need to call something like [createDocument](https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation/createDocument) so we can specify the doctype.

**Comment by meche-gh** [comment]
The joys of the DOM API 😄 /s 

Once we've created a real standardised document we can pass it with [`srcdoc`](https://stackoverflow.com/questions/14186070/javascript-create-an-iframe-with-strict-doctype/28604485#28604485)

**Comment by meche-gh** [comment]
I'll handle this and the last comments of #70 now.

**Pull request merged**
