### PR TITLE
added "including same origin and blob iframes"

### PR DESCRIPTION
**Pull request by mfyuce**
added "including same origin and blob iframes", if somebody needed the support and stumble upon here...

### CODE REVIEW

**Review by IDisposable — APPROVED** [review]

**Comment by AnnoyingTechnology** [comment]
doesn't seem to build 
Screenshot from 2021-09-28 15-34-11

**Comment by mfyuce** [comment]
Will check and inform.

**Comment by AnnoyingTechnology** [comment]
https://github.com/1904labs/dom-to-image-more/pull/49

**Comment by mfyuce** [comment]
Thanks.

**Pull request merged**
