### PR TITLE
Added alternative solutions to fix #14 in README.md 

### LINKED ISSUE #14: Load remote images CORS
HI, 
I have an issue with Angular 8+

`Access to XMLHttpRequest at 'http://example.com/images/example_image.png' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Is there a way to add a header to requests maybe?
Or what can I do with that?

### Browsers

- [ ] Chrome 49+  
- [ ] Firefox 45+

### PR DESCRIPTION
**Pull request by emrecoban**
Many people are encountering the same issue. I have added solutions to help them quickly resolve the problem.

### CODE REVIEW

**Comment by IDisposable** [comment]
Excellent, thanks! Can you squash those commits and force push please.

**Comment by emrecoban** [comment]
You're welcome. The pull request is awaiting your approval.

**Comment by IDisposable** [comment]
Merged, thanks. I'm updating the docs now... I have your name as Emre Coban, but not sure that guess is correct

**Comment by emrecoban** [comment]
> Merged, thanks. I'm updating the docs now... I have your name as Emre Coban, but not sure that guess is correct (Sheperd?)

Thank you. Yes, my name is officially Emre Coban (Coban means "Shepherd" in English).

**Pull request merged**
